---

- name: Current keypair
  authorized_key:
    user: "{{ lookup('env','USER') }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/current_id_rsa.pub') }}"

- name: Previous keypair
  authorized_key:
    user: "{{ lookup('env','USER') }}"
    state: absent
    key: "{{ lookup('file', '~/.ssh/previous_id_rsa.pub') }}"

- name: RedHat
  include: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Windows
  include: windows.yml
  when: ansible_os_family == 'Windows'
