- name: wait for {{ inventory_hostname }}
  wait_for_connection:

- name: change hostname to {{ inventory_hostname }}
  hostname:
    name: '{{ inventory_hostname }}'
  register: hostname

- name: install agent dependencies (redhat)
  yum:
    name: '{{ artifactory_url }}{{ item.name }}'
    state: installed
    validate_certs: no
    disable_plugin: "yum-rhn-plugin"
    disablerepo: "rhel-8-appstream-rhui-rpms,rhel-8-baseos-rhui-rpms,rhui-client-config-server-8"
  with_items:
    - '{{ redhat_agent_dependencies }}'

- name: look for nvme devices
  command: nvme list
  register: nvme_exist
  changed_when: False
  check_mode: no

- name: map-ebs-nvme automation
  block:
    - name: copy map-ebs-nvme
      copy:
        src: files/map-ebs-nvme.sh
        dest: "/usr/local/bin/map-ebs-nvme"
        owner: root
        group: root
        mode: 0755

    - name: configure map-ebs-nvme rules
      copy:
        src: files/map-ebs-nvme.rules
        dest: "/etc/udev/rules.d/map-ebs-nvme.rules"
        owner: root
        group: root
        mode: 0644

    - name: run map-ebs-nvme
      command: /usr/local/bin/map-ebs-nvme

  when: not(nvme_exist.stdout | regex_search('No NVMe devices detected.'))
