# base configuration
- name: wait for {{ inventory_hostname }}
  wait_for_connection:
    delay: 30
    timeout: 300

# hostname configuration
- name: change hostname to {{ inventory_hostname }}
  hostname:
    name: '{{ inventory_hostname }}'
  register: hostname

# /etc/resolve.conf configuration
- name: configure resolv.conf
  template:
    src: "resolv.conf.j2"
    dest: "/etc/resolv.conf"
    mode: "0644"
  become: true

# fireeye install
- name: install fireeye
  shell:
    cmd: rpm -ivh /utilities/vmtemplateinfo/fireeye/xagt.rpm

- name: configure fireeye
  shell:
    cmd: /opt/fireeye/bin/xagt -i /utilities/vmtemplateinfo/fireeye/agent_config.json

- name: start fireeye
  shell:
    cmd: systemctl start xagt

- name: check status for fireeye
  shell:
    cmd: systemctl status xagt

# nessus install
- name: install nessus
  shell:
    cmd: rpm --upgrade --oldpackage --verbose /utilities/vmtemplateinfo/nessus/NessusAgent.rpm

- name: link nessus
  shell:
    cmd: /opt/nessus_agent/sbin/nessuscli agent link --key={{ agent_key }} --host={{ agent_host }} --port={{ agent_port }}

- name: start nessus
  shell:
    cmd: systemctl start nessusagent.service

- name: check status for nessus
  shell:
    cmd: systemctl status nessusagent.service

- name: check agent registration status for nessus
  shell:
    cmd: /opt/nessus_agent/sbin/nessuscli agent status

# endgame install
- name: endgame install config
  shell:
    cmd: chmod 777 /utilities/vmtemplateinfo/endgame/SensorLinuxInstaller-Detect-Policy

- name: endgame policy config
  shell:
    cmd: chmod 777 /utilities/vmtemplateinfo/endgame/SensorLinuxInstaller-Detect-Policy.cfg

- name: endgame install
  shell:
    cmd: /utilities/vmtemplateinfo/endgame/SensorLinuxInstaller-Detect-Policy -c /utilities/vmtemplateinfo/endgame/SensorLinuxInstaller-Detect-Policy.cfg -k {{ endgame_key }} -l /utilities/vmtemplateinfo/endgame/install.log
