# wait for connection
- name: wait for {{ inventory_hostname }}
  wait_for_connection:

# base configuration
- name: set the default shell to powershell
  win_regedit:
    path: HKLM:\SOFTWARE\OpenSSH
    name: DefaultShell
    data: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    type: string
    state: present

# firewall configuration
- name: enable firewall for domain, public and private profiles
  win_firewall:
    state: enabled
    profiles:
    - Domain
    - Private
    - Public

- name: default allow all in rule
  win_firewall_rule:
    name: allow_all_in
    localport: any
    action: allow
    direction: in
    protocol: any
    state: present
    enabled: yes

- name: default allow all out rule
  win_firewall_rule:
    name: allow_all_out
    localport: any
    action: allow
    direction: out
    protocol: any
    state: present
    enabled: yes

# hostname configuration
- name: change hostname to {{ inventory_hostname }}
  win_hostname:
    name: '{{ inventory_hostname }}'
  register: hostname

- name: reboot
  win_reboot:
  when: hostname.reboot_required

# domain configuration
- name: add {{ inventory_hostname }} to the domain
  win_domain_membership:
    dns_domain_name: '{{ qaent_domain.domain }}'
    hostname: '{{ inventory_hostname }}'
    domain_admin_user: '{{ qaent_domain.username }}'
    domain_admin_password: '{{ qaent_domain.password }}'
    domain_ou_path: '{{ qaent_domain.ou }}'
    state: domain
  register: domain_state

- win_reboot:
  when: domain_state.reboot_required

# add local debug user for testing and agent validation
- name: create local user for debug purposes
  win_user:
    name: '{{ local_users.username }}'
    password: '{{ local_users.password }}'
    state: present
    description: "local debug user for testing and agent validation"
    groups:
      - '{{ local_users.group1 }}'
      - '{{ local_users.group2 }}'
